@ECHO off

REM Variables
SET "RAIDENHTTP_PROJ_NAME=RaidenPS_HTTP"
SET "RAIDENHTTP_PROJ_DIR=RaidenHTTPS"
SET "RAIDENHTTP_PROTO_CLASS=raidenhttp.cache.protos"
SET "RAIDENHTTP_PROTO_OUT=out/raidenhttp"
SET "RAIDENGAME_PROTO_OUT=out/raidenemu"
SET "RAIDENGAME_PROJ_NAME=RaidenEmu"
SET "RAIDENGAME_PROJ_DIR=RaidenEmu"
SET "RAIDENGAME_PROTO_CLASS=raidenemu.cache.protobuf"

REM Environment
if /i "%~1"=="print" (
	ECHO ENVIRONMENT
	ECHO RAIDENHTTP_PROJ_NAME:         			%RAIDENHTTP_PROJ_NAME%
	ECHO RAIDENHTTP_PROJ_DIR:         			%RAIDENHTTP_PROJ_DIR%
	ECHO RAIDENHTTP_PROTO_CLASS:         		%RAIDENHTTP_PROTO_CLASS%
	ECHO RAIDENHTTP_PROTO_OUT:         			%RAIDENHTTP_PROTO_OUT%
	ECHO RAIDENGAME_PROTO_OUT:         			%RAIDENGAME_PROTO_OUT%
	ECHO RAIDENGAME_PROJ_NAME:         			%RAIDENGAME_PROJ_NAME%
	ECHO RAIDENGAME_PROJ_DIR:         			%RAIDENGAME_PROJ_DIR%
	ECHO RAIDENGAME_PROTO_CLASS:         		%RAIDENGAME_PROTO_CLASS%
	echo:
	echo:
)